# Travis CI script
# This is a skeleton created by zproject.
# You can add hand-written code here.

language: c

cache: ccache

os:
- linux

sudo: false

# Set CI_TIME=true to enable build-step profiling in Travis
# Set CI_TRACE=true to enable shell script tracing in Travis
# Set CI_CONFIG_QUIET=true to enable "configure --quiet" (only report stderr)
env:
  global:
    # Note: Secure variables must be global!
    #
    # tokens to deploy releases on OBS.
    # 1) Create 2 OBS tokens with osc token --create network:messaging:zeromq:release-<stable|draft> <project>
    #    encrypt them with travis encrypt --org -r <org>/<repo> OBS_<STABLE|DRAFT>_TOKEN="<token>"
    # 2) Uncomment the "secure" lines and paste the encrypted tokens
    - secure: iH2hcROKwJygeLl+vwa+UPdrrc9iwGr0YZLacIEDUL1KzhkpUvgkYQU2TS0nnPJyRVcwRRw8IkX5ScWTl+r4rmtkbwrUik6mkhndQHB+lI8c6rBSXDh1broxOp3I/2H8OTs7xy+bzdos+FuP2bc47O4jlbqx15vr58JoM8Ew9tg=
    - secure: FWkD9I8FdX1rIR29CcImL9p5Nvi4VWosn1pV8N9LPi+r/lLtoi0B++zrSUPlZU+cscrMdxJ4XOpUoSw00yshkRbKWFYFp2dFNkRlW116F+GV5qwrFqUXrgk0ppvjDqLSmypfXQpNgQMycywLhoZ2EnQelWZN4D7Up0JBSD7JzAE=
    - secure: I+az1ijGwS+ZLtgi8Z857VnnlaR0AFuCHvPeDz/XCgpiF4XpciLTiY4Igox8ho+NPBNdwHHBZ8qzhsG+5C9W6e9qJ9ZQfEiaYLqS3BQeLtXTFsEujsazrEhv3C8VpboDGMQH2Berd9U95ud1hqpQf424ugbY/snm9qw2GZ+G8kY=
    - CI_TIME=false
    - CI_TRACE=false
    - CI_CONFIG_QUIET=true
  matrix:
    - BUILD_TYPE=default
    - BUILD_TYPE=cmake
    - BUILD_TYPE=check_zproject

matrix:
  include:
  - env: BUILD_TYPE=valgrind
    os: linux
    addons:
      apt:
        sources:
        - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/ ./'
          key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/Release.key'
        packages:
        - valgrind
        - libzmq3-dev
        - libczmq-dev
  - env: BUILD_TYPE=check_zproto
    os: linux
    services: docker
    addons:
      apt:

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/Release.key'
    packages:
    - asciidoc
    - xmlto
    - generator-scripting-language
    - zproject
    - libzmq3-dev
    - libczmq-dev

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils ; fi
- if [ $TRAVIS_OS_NAME == "osx" -a $BUILD_TYPE == "valgrind" ] ; then brew install valgrind ; fi

# Hand off to generated script for each BUILD_TYPE
script: ./ci_build.sh
before_deploy: . ./ci_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: LtmfBJePKkua5YNBidT8Qm53UIll3eUSKuIMG5EQ17t/tr0RXXm4NeRFPUReMLUSBDF6TojM0K0rTYwC8i66h5nZ3q8n6bn1nTup+nJdqeW3zhH3MLLLC+PfOt7I8a9uJ5G6NqzrxN8AY73cvvZ/pBZb79CWobEruRYK2Cb7GWE=
  file_glob: true
  file: ${MALAMUTE_DEPLOYMENT}
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME =~ (linux) && $BUILD_TYPE =~ (default)
