# Travis CI script

language: c

sudo: false

env:
- BUILD_TYPE=default
- BUILD_TYPE=check_zproject

services: 
- docker

addons:
  apt:
    packages:
    - uuid-dev
    - valgrind

script: ./ci_build.sh
