# Travis CI script

language: c

sudo: false

env:
- BUILD_TYPE=default
- BUILD_TYPE=check_zproject
- BUILD_TYPE=check_zproto
- BUILD_TYPE=valgrind

services: 
- docker

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
    packages:
    - uuid-dev
    - valgrind
    - zproject
    - libczmq-dev

script: ./ci_build.sh
